### ISSUE TITLE
add new field precio to vid model 

### ISSUE THREAD

**Issue by Japoivvb** [Pxios01/DAM2T-M06-UF2-P2-Viticulture#4]
1. add double price attribute to vid model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Pxios01** [comment]
![image](https://github.com/Pxios01/DAM2T-M06-UF2-P2-Viticulture/assets/153656021/d9f02e3a-3594-4eef-97b5-b3b8005ec613)

**Comment by Japoivvb** [comment]
1. ko, price values should come from input table Entrada and they should be informed in vids table also
2. ok
3. ok
4. ok
5. ok
